In [98]:
import pandas as pd
#import excel spreadsheet
df = pd.read_excel(r"Copy of Oilcomp EN_200 MS xxxx_v110-Dr.Hii.xlsm", sheet_name="Database")
df = df.iloc[9:154,]
df.dropna()
df = df.loc[:, (df != 0).all(axis=0)]
print(df)
df.to_csv('file2.csv', header=True, index=False)
df.set_index("DATABASE",inplace=True)

C:\Users\zanyi\AppData\Roaming\Python\Python310\site-packages\openpyxl\reader\workbook.py:118: UserWarning: Print area cannot be set to Defined name: Database!$A:$C.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

              DATABASE Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
9           1_1-M-Adam        135          H      12.22      26414      12.22
10       2_1,2-DM-Adam        149          H      15.18      17969      15.18
11             3_i-C13        113          H      15.56      37058      15.55
12      4_2-M-Tetralin        104          H      15.46      33278      15.46
13   5_c-1,3,4-TM-Adam        163          H      15.38      10710      15.37
..                 ...        ...        ...        ...        ...        ...
149      142_25nor30ab        177          H      46.45       7182      46.44
150          143_29aaR        217          H      46.78      15937      46.76
151           144_29Ts        191          H      46.88      19032      46.86
152           145_30ba        191          H      48.24      14691      48.22
153          146_32abS        191          H      49.84      48332      49.83

    Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ... Unnamed: 18 Unnamed: 19  \
9         3004      12.22      14631      12.22  ...         NaN         NaN
10        2723      15.17       9497      15.17  ...         NaN         NaN
11        2108      15.55      10892      15.55  ...         NaN         NaN
12        8771      15.46      33691      15.46  ...         NaN         NaN
13        1912      15.37       6980      15.37  ...         NaN         NaN
..         ...        ...        ...        ...  ...         ...         ...
149       9078      46.45      22521      46.45  ...         NaN         NaN
150       3594      46.76       9867      46.76  ...         NaN         NaN
151      13814      46.86      34721      46.86  ...         NaN         NaN
152       7697      48.23      21271      48.23  ...         NaN         NaN
153      14536      49.83      40687      49.83  ...         NaN         NaN

     Unnamed: 20  Unnamed: 21 Unnamed: 22  Unnamed: 23 Unnamed: 24  \
9            NaN          NaN         NaN          NaN         NaN
10           NaN          NaN         NaN          NaN         NaN
11           NaN          NaN         NaN          NaN         NaN
12           NaN          NaN         NaN          NaN         NaN
13           NaN          NaN         NaN          NaN         NaN
..           ...          ...         ...          ...         ...
149          NaN          NaN         NaN          NaN         NaN
150          NaN          NaN         NaN          NaN         NaN
151          NaN          NaN         NaN          NaN         NaN
152          NaN          NaN         NaN          NaN         NaN
153          NaN          NaN         NaN          NaN         NaN

     Unnamed: 25 Unnamed: 26  Unnamed: 27
9            NaN         NaN          NaN
10           NaN         NaN          NaN
11           NaN         NaN          NaN
12           NaN         NaN          NaN
13           NaN         NaN          NaN
..           ...         ...          ...
149          NaN         NaN          NaN
150          NaN         NaN          NaN
151          NaN         NaN          NaN
152          NaN         NaN          NaN
153          NaN         NaN          NaN

[145 rows x 28 columns]

In [99]:
columnIndex = 0
samplecount = 0
for i in range(3,len(df.columns),2):
    df.columns.values[i-1]=f"sample{samplecount}Ret"
    df.columns.values[i]=f"sample{samplecount}Value"
    samplecount+=1

print(df.loc["1_1-M-Adam"])
display(df)

Unnamed: 1         135
Unnamed: 2           H
sample0Ret       12.22
sample0Value     26414
sample1Ret       12.22
sample1Value      3004
sample2Ret       12.22
sample2Value     14631
sample3Ret       12.22
sample3Value     23763
sample4Ret         NaN
sample4Value       NaN
sample5Ret         NaN
sample5Value       NaN
sample6Ret         NaN
sample6Value       NaN
sample7Ret         NaN
sample7Value       NaN
sample8Ret         NaN
sample8Value       NaN
sample9Ret         NaN
sample9Value       NaN
sample10Ret        NaN
sample10Value      NaN
sample11Ret        NaN
sample11Value      NaN
Unnamed: 27        NaN
Name: 1_1-M-Adam, dtype: object

,Unnamed: 1,Unnamed: 2,sample0Ret,sample0Value,sample1Ret,sample1Value,sample2Ret,sample2Value,sample3Ret,sample3Value,...,sample7Value,sample8Ret,sample8Value,sample9Ret,sample9Value,sample10Ret,sample10Value,sample11Ret,sample11Value,Unnamed: 27
DATABASE,,,,,,,,,,,,,,,,,,,,,
1_1-M-Adam,135,H,12.22,26414,12.22,3004,12.22,14631,12.22,23763,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"2_1,2-DM-Adam",149,H,15.18,17969,15.18,2723,15.17,9497,15.17,12903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3_i-C13,113,H,15.56,37058,15.55,2108,15.55,10892,15.55,14144,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4_2-M-Tetralin,104,H,15.46,33278,15.46,8771,15.46,33691,15.46,41435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"5_c-1,3,4-TM-Adam",163,H,15.38,10710,15.37,1912,15.37,6980,15.37,8799,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142_25nor30ab,177,H,46.45,7182,46.44,9078,46.45,22521,46.45,24265,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143_29aaR,217,H,46.78,15937,46.76,3594,46.76,9867,46.76,10902,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144_29Ts,191,H,46.88,19032,46.86,13814,46.86,34721,46.86,34326,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145_30ba,191,H,48.24,14691,48.22,7697,48.23,21271,48.23,22241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146_32abS,191,H,49.84,48332,49.83,14536,49.83,40687,49.83,45031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
def removeFN(string):
    string=string[string.find("_")+1:]
    return string

def ratio(compound1,compound2,sample=0,Normative=True):
    print("Starting the ratio of "+compound1+" and "+compound2)
    if df.loc[compound1][f"sample{sample}Value"]>1 and df.loc[compound2][f"sample{sample}Value"]>1:
        if Normative:
            return ["NR-"+removeFN(compound1)+"/"+removeFN(compound2), 100*(df.loc[compound1][f"sample{sample}Value"]/df.loc[compound2][f"sample{sample}Value"])]
        else:
            return [removeFN(compound1)+"/"+removeFN(compound2), 100*(df.loc[compound1][f"sample{sample}Value"]/df.loc[compound2][f"sample{sample}Value"])]
    else:
        if Normative:
            return ["NR-"+removeFN(compound1)+"/"+removeFN(compound2), 0.0001]
        else:
            return [removeFN(compound1)+"/"+removeFN(compound2), 0.0001]

def NormaliseToBS10(compound, sample1=1, sample2=2):
    print("Normalising "+compound+" to BS10")
    if df.loc["24_BS10"][f"sample{sample1}Value"]>1:
        return [df.loc[compound][f"sample{sample1}Ret"], compound, df.loc[compound][f"sample{sample1}Value"], df.loc[compound][f"sample{sample2}Value"], df.loc[compound][f"sample{sample1}Value"]/df.loc["24_BS10"][f"sample{sample1}Value"]*df.loc["24_BS10"][f"sample{sample2}Value"]]
    else:
        return [df.loc[compound][f"sample{sample1}Ret"], compound, df.loc[compound][f"sample{sample1}Value"], df.loc[compound][f"sample{sample2}Value"], 0.001]
    
def NormaliseToPhytane(compound, sample1=1, sample2=2):
    print("Normalising "+compound+" to Phytane")
    if df.loc["33_Phy"][f"sample{sample1}Value"]>1:
        return [df.loc[compound][f"sample{sample1}Ret"], compound, df.loc[compound][f"sample{sample1}Value"], df.loc[compound][f"sample{sample2}Value"], df.loc[compound][f"sample{sample1}Value"]/df.loc["33_Phy"][f"sample{sample1}Value"]*df.loc["33_Phy"][f"sample{sample2}Value"]]
    else:
        return [df.loc[compound][f"sample{sample1}Ret"], compound, df.loc[compound][f"sample{sample1}Value"], df.loc[compound][f"sample{sample2}Value"], 0.001]

def NormaliseToHopane(compound, sample1=1, sample2=3):
    print("Normalising "+compound+" to Hopane")
    if df.loc["64_30ab"][f"sample{sample1}Value"]>1:
        return [df.loc[compound][f"sample{sample1}Ret"], compound, df.loc[compound][f"sample{sample1}Value"], df.loc[compound][f"sample{sample2}Value"], df.loc[compound][f"sample{sample1}Value"]/df.loc["64_30ab"][f"sample{sample1}Value"]*df.loc["64_30ab"][f"sample{sample2}Value"]]
    else:
        return [df.loc[compound][f"sample{sample1}Ret"], compound, df.loc[compound][f"sample{sample1}Value"], df.loc[compound][f"sample{sample2}Value"], 0.001]

In [101]:
def createRatio(sampleNo=0):
    NormarativeRatio=[]
    NormarativeRatio.append(ratio("1_1-M-Adam","2_1,2-DM-Adam",sampleNo))
    NormarativeRatio.append(ratio("1_1-M-Adam","8_2-E-Adam",sampleNo))
    NormarativeRatio.append(ratio("3_i-C13","4_2-M-Tetralin",sampleNo))
    NormarativeRatio.append(ratio("5_c-1,3,4-TM-Adam","8_2-E-Adam",sampleNo)) #checked
    NormarativeRatio.append(ratio("6_C6_Benz","12_C7_Benz",sampleNo))
    NormarativeRatio.append(ratio("8_2-E-Adam","7_i-C14",sampleNo))
    NormarativeRatio.append(ratio("9_BS1","11_BS2",sampleNo))
    NormarativeRatio.append(ratio("10_C3-de peak","11_BS2",sampleNo)) #checked
    NormarativeRatio.append(ratio("13_B","14_2-E-N",sampleNo))
    NormarativeRatio.append(ratio("14_2-E-N","15_2,6+2,7-DM-N",sampleNo))
    NormarativeRatio.append(ratio("17_BS4","18_BS5",sampleNo))
    NormarativeRatio.append(ratio("16_Br-Alk 169-3","20_n-C15",sampleNo))
    NormarativeRatio.append(ratio("18_BS5","19_BS6",sampleNo)) #checked
    NormarativeRatio.append(ratio("21_BS8","22_BS9",sampleNo))
    NormarativeRatio.append(ratio("23_m-C8-Tol","25_o-C8-Tol",sampleNo))
    NormarativeRatio.append(ratio("24_BS10","26_Norpri",sampleNo))
    NormarativeRatio.append(ratio("26_Norpri","27_m-C9-Tol",sampleNo))
    NormarativeRatio.append(ratio("28_C10_Benz","31_n-C11-CyC6",sampleNo))
    NormarativeRatio.append(ratio("29_n-C17","30_Pri",sampleNo)) #checked
    NormarativeRatio.append(ratio("30_Pri","33_Phy",sampleNo))
    NormarativeRatio.append(ratio("32_n-C18","33_Phy",sampleNo))
    NormarativeRatio.append(ratio("34_4-M-Dbt","37_1-M-Dbt",sampleNo))
    NormarativeRatio.append(ratio("35_Br-Alk 225-3","36_n-C19",sampleNo))
    NormarativeRatio.append(ratio("38_2-M-Phe","40_1-M-Phe",sampleNo))
    NormarativeRatio.append(ratio("39_FAME 16:0","43_FAME 18:0",sampleNo))
    NormarativeRatio.append(ratio("41_C2-dbt_s","42_C2-phe_s",sampleNo)) #checked
    NormarativeRatio.append(ratio("44_2-M-Fl","49_4-M-Py",sampleNo))
    NormarativeRatio.append(ratio("45_C15-Benz","53_C17-Benz",sampleNo))
    NormarativeRatio.append(ratio("46_BaF","49_4-M-Py",sampleNo))
    NormarativeRatio.append(ratio("47_Retene","59_29bbR+S",sampleNo))
    NormarativeRatio.append(ratio("48_2-M-Py","49_4-M-Py",sampleNo))
    NormarativeRatio.append(ratio("50_1-M-Py","49_4-M-Py",sampleNo))
    NormarativeRatio.append(ratio("51_C23Tr","52_C24Tr",sampleNo))
    NormarativeRatio.append(ratio("54_27bbR+S","59_29bbR+S",sampleNo))
    NormarativeRatio.append(ratio("55_27Ts","64_30ab",sampleNo))
    NormarativeRatio.append(ratio("56_SC26 TA","58_RC26TA+SC27 TA",sampleNo)) #checked
    NormarativeRatio.append(ratio("57_27Tm","64_30ab",sampleNo))
    NormarativeRatio.append(ratio("60_28ab","64_30ab",sampleNo))
    NormarativeRatio.append(ratio("61_SC28 TA","58_RC26TA+SC27 TA",sampleNo))
    NormarativeRatio.append(ratio("62_29ab","64_30ab",sampleNo))
    NormarativeRatio.append(ratio("63_30O","64_30ab",sampleNo))
    NormarativeRatio.append(ratio("65_RC28 TA","58_RC26TA+SC27 TA",sampleNo))
    NormarativeRatio.append(ratio("66_31abS","64_30ab",sampleNo))
    NormarativeRatio.append(ratio("67_30G","64_30ab",sampleNo)) #checked

    InformativeRatio=[]
    InformativeRatio.append(ratio("68_De", "1_1-M-Adam", sampleNo, Normative=False))
    InformativeRatio.append(ratio("1_1-M-Adam", "71_2-M-Adam", sampleNo, Normative=False))
    InformativeRatio.append(ratio("69_1,3,5-TM-Adam", "75_tr-1,4-DM-Adam", sampleNo, Normative=False))
    InformativeRatio.append(ratio("69_1,3,5-TM-Adam", "76_1,3,6-TM-Adam", sampleNo, Normative=False))
    InformativeRatio.append(ratio("70_C1-de_s", "77_C2-de_s", sampleNo, Normative=False))
    InformativeRatio.append(ratio("72_Tetralin", "4_2-M-Tetralin", sampleNo, Normative=False))
    InformativeRatio.append(ratio("79_1,2,5,7-TeM-Adam ", "8_2-E-Adam", sampleNo, Normative=False))
    InformativeRatio.append(ratio("79_1,2,5,7-TeM-Adam ", "24_BS10", sampleNo, Normative=False))
    InformativeRatio.append(ratio("81_m-C6-Tol", "24_BS10", sampleNo, Normative=False))
    InformativeRatio.append(ratio("81_m-C6-Tol", "83_ o-C6-Tol", sampleNo, Normative=False))
    InformativeRatio.append(ratio("12_C7_Benz", "28_C10_Benz", sampleNo, Normative=False))
    InformativeRatio.append(ratio("87_BS3", "18_BS5", sampleNo, Normative=False))
    InformativeRatio.append(ratio("86_1,6-DM-N", "85_1,3+1,7-DM-N", sampleNo, Normative=False))
    InformativeRatio.append(ratio("89_ANY", "92_1,2 -DM-N", sampleNo, Normative=False))
    InformativeRatio.append(ratio("95_ Diam", "97_4-M-Diam", sampleNo, Normative=False))
    InformativeRatio.append(ratio("96_FAME 12:0", "39_FAME 16:0", sampleNo, Normative=False))
    InformativeRatio.append(ratio("98_1,3,7-TM-N", "99_1,3,6-TM-N", sampleNo, Normative=False)) #checked
    InformativeRatio.append(ratio("21_BS8", "24_BS10", sampleNo, Normative=False))
    InformativeRatio.append(ratio("102_8H-A", "104_8H-Phe", sampleNo, Normative=False))
    InformativeRatio.append(ratio("103_1-M-F", "104_8H-Phe", sampleNo, Normative=False))
    InformativeRatio.append(ratio("105_FAME 14:0", "39_FAME 16:0", sampleNo, Normative=False))
    InformativeRatio.append(ratio("112_FAME 16:1", "39_FAME 16:0", sampleNo, Normative=False))
    InformativeRatio.append(ratio("114_1-E-Phe", "115_1,7 DM-Phe", sampleNo, Normative=False))
    InformativeRatio.append(ratio("116_C3-dbt_s", "121_C3-phe_s", sampleNo, Normative=False))
    InformativeRatio.append(ratio("117_FAME 18:2", "43_FAME 18:0", sampleNo, Normative=False))
    InformativeRatio.append(ratio("118_FAME 18:1 + 18:3", "43_FAME 18:0", sampleNo, Normative=False))
    InformativeRatio.append(ratio("120_C21Tr", "51_C23Tr", sampleNo, Normative=False))
    InformativeRatio.append(ratio("51_C23Tr", "131_Phy-Tol", sampleNo, Normative=False))
    InformativeRatio.append(ratio("125_FAME 20:0", "43_FAME 18:0", sampleNo, Normative=False))
    InformativeRatio.append(ratio("128_C20TA", "130_C21 TA", sampleNo, Normative=False))
    InformativeRatio.append(ratio("130_C21 TA", "58_RC26TA+SC27 TA", sampleNo, Normative=False))
    InformativeRatio.append(ratio("135_C28 (22S)", "64_30ab", sampleNo, Normative=False))
    InformativeRatio.append(ratio("137_BePy", "138_BaPy ", sampleNo, Normative=False))
    InformativeRatio.append(ratio("141_29aaS", "143_29aaR", sampleNo, Normative=False)) #checked
    infor = pd.DataFrame(InformativeRatio, columns=["Compounds","ratio"])
    norm = pd.DataFrame(NormarativeRatio, columns=["Compounds","ratio"])
    fin = pd.concat([norm,infor])
    return [fin,infor,norm]

In [102]:
sample1ratio=1 #important
sample2ratio=2
A=createRatio(sample1ratio)[0]
B=createRatio(sample2ratio)[0]
A = A.assign(ratio2=B.loc[:,'ratio'])
A.columns.values[1] = "A"
A.columns.values[2] = "B"

NormalisedToBS10=[]
sample1BS10=1 #important
sample2BS10=2
for rows in df.index:
    NormalisedToBS10.append(NormaliseToBS10(rows,sample1BS10,sample2BS10))
BS10DataFrame=pd.DataFrame(NormalisedToBS10,columns=[f"RetentionTime Sample {sample1BS10}", "Compounds", "A", "B", "NormalisedToBS10"])

NormalisedToPhytane=[]
sample1Phy=1 #important
sample2Phy=2
for rows in df.index:
    NormalisedToPhytane.append(NormaliseToPhytane(rows,sample1Phy,sample2Phy))
PhytaneDataFrame=pd.DataFrame(NormalisedToPhytane,columns=[f"RetentionTime Sample {sample1Phy}", "Compounds", "A", "B", "NormalisedToPhytane"])

NormalisedToHopane=[]
sample1Hopane=1 #important
sample2Hopane=3
for rows in df.index:
    NormalisedToHopane.append(NormaliseToHopane(rows,sample1,sample2))
HopaneDataFrame=pd.DataFrame(NormalisedToHopane,columns=[f"RetentionTime Sample {sample1}", "Compounds", "A", "B", "NormalisedToHopane"])

Starting the ratio of 1_1-M-Adam and 2_1,2-DM-Adam
Starting the ratio of 1_1-M-Adam and 8_2-E-Adam
Starting the ratio of 3_i-C13 and 4_2-M-Tetralin
Starting the ratio of 5_c-1,3,4-TM-Adam and 8_2-E-Adam
Starting the ratio of 6_C6_Benz and 12_C7_Benz
Starting the ratio of 8_2-E-Adam and 7_i-C14
Starting the ratio of 9_BS1 and 11_BS2
Starting the ratio of 10_C3-de peak and 11_BS2
Starting the ratio of 13_B and 14_2-E-N
Starting the ratio of 14_2-E-N and 15_2,6+2,7-DM-N
Starting the ratio of 17_BS4 and 18_BS5
Starting the ratio of 16_Br-Alk 169-3 and 20_n-C15
Starting the ratio of 18_BS5 and 19_BS6
Starting the ratio of 21_BS8 and 22_BS9
Starting the ratio of 23_m-C8-Tol and 25_o-C8-Tol
Starting the ratio of 24_BS10 and 26_Norpri
Starting the ratio of 26_Norpri and 27_m-C9-Tol
Starting the ratio of 28_C10_Benz and 31_n-C11-CyC6
Starting the ratio of 29_n-C17 and 30_Pri
Starting the ratio of 30_Pri and 33_Phy
Starting the ratio of 32_n-C18 and 33_Phy
Starting the ratio of 34_4-M-Dbt and 37_1-M-Dbt
Starting the ratio of 35_Br-Alk 225-3 and 36_n-C19
Starting the ratio of 38_2-M-Phe and 40_1-M-Phe
Starting the ratio of 39_FAME 16:0 and 43_FAME 18:0
Starting the ratio of 41_C2-dbt_s and 42_C2-phe_s
Starting the ratio of 44_2-M-Fl and 49_4-M-Py
Starting the ratio of 45_C15-Benz and 53_C17-Benz
Starting the ratio of 46_BaF and 49_4-M-Py
Starting the ratio of 47_Retene and 59_29bbR+S
Starting the ratio of 48_2-M-Py and 49_4-M-Py
Starting the ratio of 50_1-M-Py and 49_4-M-Py
Starting the ratio of 51_C23Tr and 52_C24Tr
Starting the ratio of 54_27bbR+S and 59_29bbR+S
Starting the ratio of 55_27Ts and 64_30ab
Starting the ratio of 56_SC26 TA and 58_RC26TA+SC27 TA
Starting the ratio of 57_27Tm and 64_30ab
Starting the ratio of 60_28ab and 64_30ab
Starting the ratio of 61_SC28 TA and 58_RC26TA+SC27 TA
Starting the ratio of 62_29ab and 64_30ab
Starting the ratio of 63_30O and 64_30ab
Starting the ratio of 65_RC28 TA and 58_RC26TA+SC27 TA
Starting the ratio of 66_31abS and 64_30ab
Starting the ratio of 67_30G and 64_30ab
Starting the ratio of 68_De and 1_1-M-Adam
Starting the ratio of 1_1-M-Adam and 71_2-M-Adam
Starting the ratio of 69_1,3,5-TM-Adam and 75_tr-1,4-DM-Adam
Starting the ratio of 69_1,3,5-TM-Adam and 76_1,3,6-TM-Adam
Starting the ratio of 70_C1-de_s and 77_C2-de_s
Starting the ratio of 72_Tetralin and 4_2-M-Tetralin
Starting the ratio of 79_1,2,5,7-TeM-Adam  and 8_2-E-Adam
Starting the ratio of 79_1,2,5,7-TeM-Adam  and 24_BS10
Starting the ratio of 81_m-C6-Tol and 24_BS10
Starting the ratio of 81_m-C6-Tol and 83_ o-C6-Tol
Starting the ratio of 12_C7_Benz and 28_C10_Benz
Starting the ratio of 87_BS3 and 18_BS5
Starting the ratio of 86_1,6-DM-N and 85_1,3+1,7-DM-N
Starting the ratio of 89_ANY and 92_1,2 -DM-N
Starting the ratio of 95_ Diam and 97_4-M-Diam
Starting the ratio of 96_FAME 12:0 and 39_FAME 16:0
Starting the ratio of 98_1,3,7-TM-N and 99_1,3,6-TM-N
Starting the ratio of 21_BS8 and 24_BS10
Starting the ratio of 102_8H-A and 104_8H-Phe
Starting the ratio of 103_1-M-F and 104_8H-Phe
Starting the ratio of 105_FAME 14:0 and 39_FAME 16:0
Starting the ratio of 112_FAME 16:1 and 39_FAME 16:0
Starting the ratio of 114_1-E-Phe and 115_1,7 DM-Phe
Starting the ratio of 116_C3-dbt_s and 121_C3-phe_s
Starting the ratio of 117_FAME 18:2 and 43_FAME 18:0
Starting the ratio of 118_FAME 18:1 + 18:3 and 43_FAME 18:0
Starting the ratio of 120_C21Tr and 51_C23Tr
Starting the ratio of 51_C23Tr and 131_Phy-Tol
Starting the ratio of 125_FAME 20:0 and 43_FAME 18:0
Starting the ratio of 128_C20TA and 130_C21 TA
Starting the ratio of 130_C21 TA and 58_RC26TA+SC27 TA
Starting the ratio of 135_C28 (22S) and 64_30ab
Starting the ratio of 137_BePy and 138_BaPy
Starting the ratio of 141_29aaS and 143_29aaR
Starting the ratio of 1_1-M-Adam and 2_1,2-DM-Adam
Starting the ratio of 1_1-M-Adam and 8_2-E-Adam
Starting the ratio of 3_i-C13 and 4_2-M-Tetralin
Starting the ratio of 5_c-1,3,4-TM-Adam and 8_2-E-Adam
Starting the ratio of 6_C6_Benz and 12_C7_Benz
Starting the ratio of 8_2-E-Adam and 7_i-C14
Starting the ratio of 9_BS1 and 11_BS2
Starting the ratio of 10_C3-de peak and 11_BS2
Starting the ratio of 13_B and 14_2-E-N
Starting the ratio of 14_2-E-N and 15_2,6+2,7-DM-N
Starting the ratio of 17_BS4 and 18_BS5
Starting the ratio of 16_Br-Alk 169-3 and 20_n-C15
Starting the ratio of 18_BS5 and 19_BS6
Starting the ratio of 21_BS8 and 22_BS9
Starting the ratio of 23_m-C8-Tol and 25_o-C8-Tol
Starting the ratio of 24_BS10 and 26_Norpri
Starting the ratio of 26_Norpri and 27_m-C9-Tol
Starting the ratio of 28_C10_Benz and 31_n-C11-CyC6
Starting the ratio of 29_n-C17 and 30_Pri
Starting the ratio of 30_Pri and 33_Phy
Starting the ratio of 32_n-C18 and 33_Phy
Starting the ratio of 34_4-M-Dbt and 37_1-M-Dbt
Starting the ratio of 35_Br-Alk 225-3 and 36_n-C19
Starting the ratio of 38_2-M-Phe and 40_1-M-Phe
Starting the ratio of 39_FAME 16:0 and 43_FAME 18:0
Starting the ratio of 41_C2-dbt_s and 42_C2-phe_s
Starting the ratio of 44_2-M-Fl and 49_4-M-Py
Starting the ratio of 45_C15-Benz and 53_C17-Benz
Starting the ratio of 46_BaF and 49_4-M-Py
Starting the ratio of 47_Retene and 59_29bbR+S
Starting the ratio of 48_2-M-Py and 49_4-M-Py
Starting the ratio of 50_1-M-Py and 49_4-M-Py
Starting the ratio of 51_C23Tr and 52_C24Tr
Starting the ratio of 54_27bbR+S and 59_29bbR+S
Starting the ratio of 55_27Ts and 64_30ab
Starting the ratio of 56_SC26 TA and 58_RC26TA+SC27 TA
Starting the ratio of 57_27Tm and 64_30ab
Starting the ratio of 60_28ab and 64_30ab
Starting the ratio of 61_SC28 TA and 58_RC26TA+SC27 TA
Starting the ratio of 62_29ab and 64_30ab
Starting the ratio of 63_30O and 64_30ab
Starting the ratio of 65_RC28 TA and 58_RC26TA+SC27 TA
Starting the ratio of 66_31abS and 64_30ab
Starting the ratio of 67_30G and 64_30ab
Starting the ratio of 68_De and 1_1-M-Adam
Starting the ratio of 1_1-M-Adam and 71_2-M-Adam
Starting the ratio of 69_1,3,5-TM-Adam and 75_tr-1,4-DM-Adam
Starting the ratio of 69_1,3,5-TM-Adam and 76_1,3,6-TM-Adam
Starting the ratio of 70_C1-de_s and 77_C2-de_s
Starting the ratio of 72_Tetralin and 4_2-M-Tetralin
Starting the ratio of 79_1,2,5,7-TeM-Adam  and 8_2-E-Adam
Starting the ratio of 79_1,2,5,7-TeM-Adam  and 24_BS10
Starting the ratio of 81_m-C6-Tol and 24_BS10
Starting the ratio of 81_m-C6-Tol and 83_ o-C6-Tol
Starting the ratio of 12_C7_Benz and 28_C10_Benz
Starting the ratio of 87_BS3 and 18_BS5
Starting the ratio of 86_1,6-DM-N and 85_1,3+1,7-DM-N
Starting the ratio of 89_ANY and 92_1,2 -DM-N
Starting the ratio of 95_ Diam and 97_4-M-Diam
Starting the ratio of 96_FAME 12:0 and 39_FAME 16:0
Starting the ratio of 98_1,3,7-TM-N and 99_1,3,6-TM-N
Starting the ratio of 21_BS8 and 24_BS10
Starting the ratio of 102_8H-A and 104_8H-Phe
Starting the ratio of 103_1-M-F and 104_8H-Phe
Starting the ratio of 105_FAME 14:0 and 39_FAME 16:0
Starting the ratio of 112_FAME 16:1 and 39_FAME 16:0
Starting the ratio of 114_1-E-Phe and 115_1,7 DM-Phe
Starting the ratio of 116_C3-dbt_s and 121_C3-phe_s
Starting the ratio of 117_FAME 18:2 and 43_FAME 18:0
Starting the ratio of 118_FAME 18:1 + 18:3 and 43_FAME 18:0
Starting the ratio of 120_C21Tr and 51_C23Tr
Starting the ratio of 51_C23Tr and 131_Phy-Tol
Starting the ratio of 125_FAME 20:0 and 43_FAME 18:0
Starting the ratio of 128_C20TA and 130_C21 TA
Starting the ratio of 130_C21 TA and 58_RC26TA+SC27 TA
Starting the ratio of 135_C28 (22S) and 64_30ab
Starting the ratio of 137_BePy and 138_BaPy
Starting the ratio of 141_29aaS and 143_29aaR
Normalising 1_1-M-Adam to BS10
Normalising 2_1,2-DM-Adam to BS10
Normalising 3_i-C13 to BS10
Normalising 4_2-M-Tetralin to BS10
Normalising 5_c-1,3,4-TM-Adam to BS10
Normalising 6_C6_Benz to BS10
Normalising 7_i-C14 to BS10
Normalising 8_2-E-Adam to BS10
Normalising 9_BS1 to BS10
Normalising 10_C3-de peak to BS10
Normalising 11_BS2 to BS10
Normalising 12_C7_Benz to BS10
Normalising 13_B to BS10
Normalising 14_2-E-N to BS10
Normalising 15_2,6+2,7-DM-N to BS10
Normalising 16_Br-Alk 169-3 to BS10
Normalising 17_BS4 to BS10
Normalising 18_BS5 to BS10
Normalising 19_BS6 to BS10
Normalising 20_n-C15 to BS10
Normalising 21_BS8 to BS10
Normalising 22_BS9 to BS10
Normalising 23_m-C8-Tol to BS10
Normalising 24_BS10 to BS10
Normalising 25_o-C8-Tol to BS10
Normalising 26_Norpri to BS10
Normalising 27_m-C9-Tol to BS10
Normalising 28_C10_Benz to BS10
Normalising 29_n-C17 to BS10
Normalising 30_Pri to BS10
Normalising 31_n-C11-CyC6 to BS10
Normalising 32_n-C18 to BS10
Normalising 33_Phy to BS10
Normalising 34_4-M-Dbt to BS10
Normalising 35_Br-Alk 225-3 to BS10
Normalising 36_n-C19 to BS10
Normalising 37_1-M-Dbt to BS10
Normalising 38_2-M-Phe to BS10
Normalising 39_FAME 16:0 to BS10
Normalising 40_1-M-Phe to BS10
Normalising 41_C2-dbt_s to BS10
Normalising 42_C2-phe_s to BS10
Normalising 43_FAME 18:0 to BS10
Normalising 44_2-M-Fl to BS10
Normalising 45_C15-Benz to BS10
Normalising 46_BaF to BS10
Normalising 47_Retene to BS10
Normalising 48_2-M-Py to BS10
Normalising 49_4-M-Py to BS10
Normalising 50_1-M-Py to BS10
Normalising 51_C23Tr to BS10
Normalising 52_C24Tr to BS10
Normalising 53_C17-Benz to BS10
Normalising 54_27bbR+S to BS10
Normalising 55_27Ts to BS10
Normalising 56_SC26 TA to BS10
Normalising 57_27Tm to BS10
Normalising 58_RC26TA+SC27 TA to BS10
Normalising 59_29bbR+S to BS10
Normalising 60_28ab to BS10
Normalising 61_SC28 TA to BS10
Normalising 62_29ab to BS10
Normalising 63_30O to BS10
Normalising 64_30ab to BS10
Normalising 65_RC28 TA to BS10
Normalising 66_31abS to BS10
Normalising 67_30G to BS10
Normalising 68_De to BS10
Normalising 69_1,3,5-TM-Adam to BS10
Normalising 70_C1-de_s to BS10
Normalising 71_2-M-Adam to BS10
Normalising 72_Tetralin to BS10
Normalising 73_c-1,4-DM-Adam to BS10
Normalising 74_N to BS10
Normalising 75_tr-1,4-DM-Adam to BS10
Normalising 76_1,3,6-TM-Adam to BS10
Normalising 77_C2-de_s to BS10
Normalising 78_tr-1,3,4-TM-Adam to BS10
Normalising 79_1,2,5,7-TeM-Adam  to BS10
Normalising 80_1-M-N to BS10
Normalising 81_m-C6-Tol to BS10
Normalising 82_Br-Alk-169-1 to BS10
Normalising 83_ o-C6-Tol to BS10
Normalising 84_i-C15 to BS10
Normalising 85_1,3+1,7-DM-N to BS10
Normalising 86_1,6-DM-N to BS10
Normalising 87_BS3 to BS10
Normalising 88_C2-bt_s to BS10
Normalising 89_ANY to BS10
Normalising 90_m-C7-Tol to BS10
Normalising 91_Br-Alk-169-2 to BS10
Normalising 92_1,2 -DM-N to BS10
Normalising 93_i-C16 to BS10
Normalising 94_ o-C7-Tol to BS10
Normalising 95_ Diam to BS10
Normalising 96_FAME 12:0 to BS10
Normalising 97_4-M-Diam to BS10
Normalising 98_1,3,7-TM-N to BS10
Normalising 99_1,3,6-TM-N to BS10
Normalising 100_ n-C9-CyC6  to BS10
Normalising 101_ o-C9-Tol to BS10
Normalising 102_8H-A to BS10
Normalising 103_1-M-F to BS10
Normalising 104_8H-Phe to BS10
Normalising 105_FAME 14:0 to BS10
Normalising 106_Br-alk-225-1  to BS10
Normalising 107_C2-f_s to BS10
Normalising 108_Br-alk-225-2 to BS10
Normalising 109_m-C11-Tol to BS10
Normalising 110_C12-Benz to BS10
Normalising 111_o-C11-Tol to BS10
Normalising 112_FAME 16:1 to BS10
Normalising 113_2-M-A to BS10
Normalising 114_1-E-Phe to BS10
Normalising 115_1,7 DM-Phe to BS10
Normalising 116_C3-dbt_s to BS10
Normalising 117_FAME 18:2 to BS10
Normalising 118_FAME 18:1 + 18:3 to BS10
Normalising 120_C21Tr to BS10
Normalising 121_C3-phe_s to BS10
Normalising 122_C4-phe_s to BS10
Normalising 123_FAME 20:1 to BS10
Normalising 124_Te-M-Phe to BS10
Normalising 125_FAME 20:0 to BS10
Normalising 126_C2-fl_s to BS10
Normalising 127_BNT to BS10
Normalising 128_C20TA to BS10
Normalising 129_C25Trab to BS10
Normalising 130_C21 TA to BS10
Normalising 131_Phy-Tol to BS10
Normalising 132_C1-chr_s to BS10
Normalising 133_27dbS to BS10
Normalising 134_27dbR to BS10
Normalising 135_C28 (22S) to BS10
Normalising 136_C29 (22S) to BS10
Normalising 137_BePy to BS10
Normalising 138_BaPy  to BS10
Normalising 139_28bbR+S to BS10
Normalising 140_28aaR to BS10
Normalising 141_29aaS to BS10
Normalising 142_25nor30ab to BS10
Normalising 143_29aaR to BS10
Normalising 144_29Ts to BS10
Normalising 145_30ba to BS10
Normalising 146_32abS to BS10
Normalising 1_1-M-Adam to Phytane
Normalising 2_1,2-DM-Adam to Phytane
Normalising 3_i-C13 to Phytane
Normalising 4_2-M-Tetralin to Phytane
Normalising 5_c-1,3,4-TM-Adam to Phytane
Normalising 6_C6_Benz to Phytane
Normalising 7_i-C14 to Phytane
Normalising 8_2-E-Adam to Phytane
Normalising 9_BS1 to Phytane
Normalising 10_C3-de peak to Phytane
Normalising 11_BS2 to Phytane
Normalising 12_C7_Benz to Phytane
Normalising 13_B to Phytane
Normalising 14_2-E-N to Phytane
Normalising 15_2,6+2,7-DM-N to Phytane
Normalising 16_Br-Alk 169-3 to Phytane
Normalising 17_BS4 to Phytane
Normalising 18_BS5 to Phytane
Normalising 19_BS6 to Phytane
Normalising 20_n-C15 to Phytane
Normalising 21_BS8 to Phytane
Normalising 22_BS9 to Phytane
Normalising 23_m-C8-Tol to Phytane
Normalising 24_BS10 to Phytane
Normalising 25_o-C8-Tol to Phytane
Normalising 26_Norpri to Phytane
Normalising 27_m-C9-Tol to Phytane
Normalising 28_C10_Benz to Phytane
Normalising 29_n-C17 to Phytane
Normalising 30_Pri to Phytane
Normalising 31_n-C11-CyC6 to Phytane
Normalising 32_n-C18 to Phytane
Normalising 33_Phy to Phytane
Normalising 34_4-M-Dbt to Phytane
Normalising 35_Br-Alk 225-3 to Phytane
Normalising 36_n-C19 to Phytane
Normalising 37_1-M-Dbt to Phytane
Normalising 38_2-M-Phe to Phytane
Normalising 39_FAME 16:0 to Phytane
Normalising 40_1-M-Phe to Phytane
Normalising 41_C2-dbt_s to Phytane
Normalising 42_C2-phe_s to Phytane
Normalising 43_FAME 18:0 to Phytane
Normalising 44_2-M-Fl to Phytane
Normalising 45_C15-Benz to Phytane
Normalising 46_BaF to Phytane
Normalising 47_Retene to Phytane
Normalising 48_2-M-Py to Phytane
Normalising 49_4-M-Py to Phytane
Normalising 50_1-M-Py to Phytane
Normalising 51_C23Tr to Phytane
Normalising 52_C24Tr to Phytane
Normalising 53_C17-Benz to Phytane
Normalising 54_27bbR+S to Phytane
Normalising 55_27Ts to Phytane
Normalising 56_SC26 TA to Phytane
Normalising 57_27Tm to Phytane
Normalising 58_RC26TA+SC27 TA to Phytane
Normalising 59_29bbR+S to Phytane
Normalising 60_28ab to Phytane
Normalising 61_SC28 TA to Phytane
Normalising 62_29ab to Phytane
Normalising 63_30O to Phytane
Normalising 64_30ab to Phytane
Normalising 65_RC28 TA to Phytane
Normalising 66_31abS to Phytane
Normalising 67_30G to Phytane
Normalising 68_De to Phytane
Normalising 69_1,3,5-TM-Adam to Phytane
Normalising 70_C1-de_s to Phytane
Normalising 71_2-M-Adam to Phytane
Normalising 72_Tetralin to Phytane
Normalising 73_c-1,4-DM-Adam to Phytane
Normalising 74_N to Phytane
Normalising 75_tr-1,4-DM-Adam to Phytane
Normalising 76_1,3,6-TM-Adam to Phytane
Normalising 77_C2-de_s to Phytane
Normalising 78_tr-1,3,4-TM-Adam to Phytane
Normalising 79_1,2,5,7-TeM-Adam  to Phytane
Normalising 80_1-M-N to Phytane
Normalising 81_m-C6-Tol to Phytane
Normalising 82_Br-Alk-169-1 to Phytane
Normalising 83_ o-C6-Tol to Phytane
Normalising 84_i-C15 to Phytane
Normalising 85_1,3+1,7-DM-N to Phytane
Normalising 86_1,6-DM-N to Phytane
Normalising 87_BS3 to Phytane
Normalising 88_C2-bt_s to Phytane
Normalising 89_ANY to Phytane
Normalising 90_m-C7-Tol to Phytane
Normalising 91_Br-Alk-169-2 to Phytane
Normalising 92_1,2 -DM-N to Phytane
Normalising 93_i-C16 to Phytane
Normalising 94_ o-C7-Tol to Phytane
Normalising 95_ Diam to Phytane
Normalising 96_FAME 12:0 to Phytane
Normalising 97_4-M-Diam to Phytane
Normalising 98_1,3,7-TM-N to Phytane
Normalising 99_1,3,6-TM-N to Phytane
Normalising 100_ n-C9-CyC6  to Phytane
Normalising 101_ o-C9-Tol to Phytane
Normalising 102_8H-A to Phytane
Normalising 103_1-M-F to Phytane
Normalising 104_8H-Phe to Phytane
Normalising 105_FAME 14:0 to Phytane
Normalising 106_Br-alk-225-1  to Phytane
Normalising 107_C2-f_s to Phytane
Normalising 108_Br-alk-225-2 to Phytane
Normalising 109_m-C11-Tol to Phytane
Normalising 110_C12-Benz to Phytane
Normalising 111_o-C11-Tol to Phytane
Normalising 112_FAME 16:1 to Phytane
Normalising 113_2-M-A to Phytane
Normalising 114_1-E-Phe to Phytane
Normalising 115_1,7 DM-Phe to Phytane
Normalising 116_C3-dbt_s to Phytane
Normalising 117_FAME 18:2 to Phytane
Normalising 118_FAME 18:1 + 18:3 to Phytane
Normalising 120_C21Tr to Phytane
Normalising 121_C3-phe_s to Phytane
Normalising 122_C4-phe_s to Phytane
Normalising 123_FAME 20:1 to Phytane
Normalising 124_Te-M-Phe to Phytane
Normalising 125_FAME 20:0 to Phytane
Normalising 126_C2-fl_s to Phytane
Normalising 127_BNT to Phytane
Normalising 128_C20TA to Phytane
Normalising 129_C25Trab to Phytane
Normalising 130_C21 TA to Phytane
Normalising 131_Phy-Tol to Phytane
Normalising 132_C1-chr_s to Phytane
Normalising 133_27dbS to Phytane
Normalising 134_27dbR to Phytane
Normalising 135_C28 (22S) to Phytane
Normalising 136_C29 (22S) to Phytane
Normalising 137_BePy to Phytane
Normalising 138_BaPy  to Phytane
Normalising 139_28bbR+S to Phytane
Normalising 140_28aaR to Phytane
Normalising 141_29aaS to Phytane
Normalising 142_25nor30ab to Phytane
Normalising 143_29aaR to Phytane
Normalising 144_29Ts to Phytane
Normalising 145_30ba to Phytane
Normalising 146_32abS to Phytane
Normalising 1_1-M-Adam to Hopane
Normalising 2_1,2-DM-Adam to Hopane
Normalising 3_i-C13 to Hopane
Normalising 4_2-M-Tetralin to Hopane
Normalising 5_c-1,3,4-TM-Adam to Hopane
Normalising 6_C6_Benz to Hopane
Normalising 7_i-C14 to Hopane
Normalising 8_2-E-Adam to Hopane
Normalising 9_BS1 to Hopane
Normalising 10_C3-de peak to Hopane
Normalising 11_BS2 to Hopane
Normalising 12_C7_Benz to Hopane
Normalising 13_B to Hopane
Normalising 14_2-E-N to Hopane
Normalising 15_2,6+2,7-DM-N to Hopane
Normalising 16_Br-Alk 169-3 to Hopane
Normalising 17_BS4 to Hopane
Normalising 18_BS5 to Hopane
Normalising 19_BS6 to Hopane
Normalising 20_n-C15 to Hopane
Normalising 21_BS8 to Hopane
Normalising 22_BS9 to Hopane
Normalising 23_m-C8-Tol to Hopane
Normalising 24_BS10 to Hopane
Normalising 25_o-C8-Tol to Hopane
Normalising 26_Norpri to Hopane
Normalising 27_m-C9-Tol to Hopane
Normalising 28_C10_Benz to Hopane
Normalising 29_n-C17 to Hopane
Normalising 30_Pri to Hopane
Normalising 31_n-C11-CyC6 to Hopane
Normalising 32_n-C18 to Hopane
Normalising 33_Phy to Hopane
Normalising 34_4-M-Dbt to Hopane
Normalising 35_Br-Alk 225-3 to Hopane
Normalising 36_n-C19 to Hopane
Normalising 37_1-M-Dbt to Hopane
Normalising 38_2-M-Phe to Hopane
Normalising 39_FAME 16:0 to Hopane
Normalising 40_1-M-Phe to Hopane
Normalising 41_C2-dbt_s to Hopane
Normalising 42_C2-phe_s to Hopane
Normalising 43_FAME 18:0 to Hopane
Normalising 44_2-M-Fl to Hopane
Normalising 45_C15-Benz to Hopane
Normalising 46_BaF to Hopane
Normalising 47_Retene to Hopane
Normalising 48_2-M-Py to Hopane
Normalising 49_4-M-Py to Hopane
Normalising 50_1-M-Py to Hopane
Normalising 51_C23Tr to Hopane
Normalising 52_C24Tr to Hopane
Normalising 53_C17-Benz to Hopane
Normalising 54_27bbR+S to Hopane
Normalising 55_27Ts to Hopane
Normalising 56_SC26 TA to Hopane
Normalising 57_27Tm to Hopane
Normalising 58_RC26TA+SC27 TA to Hopane
Normalising 59_29bbR+S to Hopane
Normalising 60_28ab to Hopane
Normalising 61_SC28 TA to Hopane
Normalising 62_29ab to Hopane
Normalising 63_30O to Hopane
Normalising 64_30ab to Hopane
Normalising 65_RC28 TA to Hopane
Normalising 66_31abS to Hopane
Normalising 67_30G to Hopane
Normalising 68_De to Hopane
Normalising 69_1,3,5-TM-Adam to Hopane
Normalising 70_C1-de_s to Hopane
Normalising 71_2-M-Adam to Hopane
Normalising 72_Tetralin to Hopane
Normalising 73_c-1,4-DM-Adam to Hopane
Normalising 74_N to Hopane
Normalising 75_tr-1,4-DM-Adam to Hopane
Normalising 76_1,3,6-TM-Adam to Hopane
Normalising 77_C2-de_s to Hopane
Normalising 78_tr-1,3,4-TM-Adam to Hopane
Normalising 79_1,2,5,7-TeM-Adam  to Hopane
Normalising 80_1-M-N to Hopane
Normalising 81_m-C6-Tol to Hopane
Normalising 82_Br-Alk-169-1 to Hopane
Normalising 83_ o-C6-Tol to Hopane
Normalising 84_i-C15 to Hopane
Normalising 85_1,3+1,7-DM-N to Hopane
Normalising 86_1,6-DM-N to Hopane
Normalising 87_BS3 to Hopane
Normalising 88_C2-bt_s to Hopane
Normalising 89_ANY to Hopane

In [103]:
def mean(row):
    return (row['A']+row['B'])/2
def absDiff(row):
    return abs(row['A']-row['B'])
def relDiff(row):
    if row['mean']>0:
        return (row['absoluteDifference']/row['mean'])*100
    else:
        return 0.0001
def flagging(row):
    if row['relativeDifference%']>14:
        return 1
    else:
        return 0

A['mean'] = A.apply(mean,axis=1)
A['absoluteDifference'] = A.apply(absDiff,axis=1)
A['relativeDifference%'] = A.apply(relDiff,axis=1)
A['14%flag'] = A.apply(flagging,axis=1)

def AfterNorm2of3BS10(row):
    if row["B"]>1:
        return 100*row["NormalisedToBS10"]/row["B"]
    else:
        return 0.0001
    
BS10DataFrame["% 2/3 After Normalisation"]=BS10DataFrame.apply(AfterNorm2of3BS10, axis=1)
display(BS10DataFrame)

def AfterNorm2of3Phy(row):
    if row["B"]>1:
        return 100*row["NormalisedToPhytane"]/row["B"]
    else:
        return 0.0001
    
PhytaneDataFrame["% 2/3 After Normalisation"]=PhytaneDataFrame.apply(AfterNorm2of3Phy, axis=1)
display(PhytaneDataFrame)

def AfterNorm2of4Hopane(row):
    if row["B"]>1:
        return 100*row["NormalisedToHopane"]/row["B"]
    else:
        return 0.0001

HopaneDataFrame["% 2/3 After Normalisation"]=HopaneDataFrame.apply(AfterNorm2of4Hopane, axis=1)
display(HopaneDataFrame)

display(A)

,RetentionTime Sample 1,Compounds,A,B,NormalisedToBS10,% 2/3 After Normalisation
0,12.22,1_1-M-Adam,3004.0,14631.0,8095.673960,55.332335
1,15.18,"2_1,2-DM-Adam",2723.0,9497.0,7338.388879,77.270600
2,15.55,3_i-C13,2108.0,10892.0,5680.985588,52.157415
3,15.46,4_2-M-Tetralin,8771.0,33691.0,23637.535387,70.159792
4,15.37,"5_c-1,3,4-TM-Adam",1912.0,6980.0,5152.772507,73.821956
...,...,...,...,...,...,...
140,46.44,142_25nor30ab,9078.0,22521.0,24464.889550,108.631453
141,46.76,143_29aaR,3594.0,9867.0,9685.703133,98.162594
142,46.86,144_29Ts,13814.0,34721.0,37228.242371,107.221112
143,48.22,145_30ba,7697.0,21271.0,20743.143299,97.518421
144,49.83,146_32abS,14536.0,40687.0,39174.006885,96.281384

,RetentionTime Sample 1,Compounds,A,B,NormalisedToPhytane,% 2/3 After Normalisation
0,12.22,1_1-M-Adam,3004.0,14631.0,7371.690406,50.384050
1,15.18,"2_1,2-DM-Adam",2723.0,9497.0,6682.128155,70.360410
2,15.55,3_i-C13,2108.0,10892.0,5172.943867,47.493058
3,15.46,4_2-M-Tetralin,8771.0,33691.0,21523.667295,63.885510
4,15.37,"5_c-1,3,4-TM-Adam",1912.0,6980.0,4691.968062,67.220173
...,...,...,...,...,...,...
140,46.44,142_25nor30ab,9078.0,22521.0,22277.032460,98.916711
141,46.76,143_29aaR,3594.0,9867.0,8819.525739,89.384065
142,46.86,144_29Ts,13814.0,34721.0,33898.978454,97.632495
143,48.22,145_30ba,7697.0,21271.0,18888.116198,88.797500
144,49.83,146_32abS,14536.0,40687.0,35670.736268,87.671090

,RetentionTime Sample 1,Compounds,A,B,NormalisedToHopane,% 2/3 After Normalisation
0,12.22,1_1-M-Adam,3004.0,14631.0,7542.017555,51.548203
1,15.18,"2_1,2-DM-Adam",2723.0,9497.0,6836.522571,71.986128
2,15.55,3_i-C13,2108.0,10892.0,5292.467712,48.590412
3,15.46,4_2-M-Tetralin,8771.0,33691.0,22020.984013,65.361622
4,15.37,"5_c-1,3,4-TM-Adam",1912.0,6980.0,4800.378683,68.773334
...,...,...,...,...,...,...
140,46.44,142_25nor30ab,9078.0,22521.0,22791.756113,101.202238
141,46.76,143_29aaR,3594.0,9867.0,9023.305956,91.449336
142,46.86,144_29Ts,13814.0,34721.0,34682.233856,99.888350
143,48.22,145_30ba,7697.0,21271.0,19324.536991,90.849217
144,49.83,146_32abS,14536.0,40687.0,36494.929154,89.696781

,Compounds,A,B,mean,absoluteDifference,relativeDifference%,14%flag
0,"NR-1-M-Adam/1,2-DM-Adam",110.319501,154.059177,132.189339,43.739676,33.088656,1
1,NR-1-M-Adam/2-E-Adam,106.751955,163.274188,135.013071,56.522234,41.864268,1
2,NR-i-C13/2-M-Tetralin,24.033748,32.329109,28.181428,8.295361,29.435560,1
3,"NR-c-1,3,4-TM-Adam/2-E-Adam",67.945984,77.893092,72.919538,9.947108,13.641211,0
4,NR-C6_Benz/C7_Benz,73.248209,94.378051,83.813130,21.129842,25.210658,1
...,...,...,...,...,...,...,...
29,C20TA/C21 TA,48.439822,46.355140,47.397481,2.084682,4.398296,0
30,C21 TA/RC26TA+SC27 TA,28.210144,25.270417,26.740280,2.939727,10.993628,0
31,C28 (22S)/30ab,3.072100,3.056887,3.064494,0.015213,0.496435,0
32,BePy/BaPy,192.205666,184.569195,188.387430,7.636471,4.053599,0
33,29aaS/29aaR,121.869783,118.151414,120.010598,3.718369,3.098367,0